import "./globals.css";
import { ThemeProvider } from "@/lib/providers/next-theme-provider";

import { Poppins } from 'next/font/google'
import { twMerge } from "tailwind-merge";

// Subsets are really important. CHECK BELOW FOR MORE INFO
const poppins = Poppins({ subsets: ['latin'],  weight: ['400', '500', '600', '700'],  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      className={twMerge('bg-background', poppins.className)}  
          >
        <ThemeProvider attribute='class' defaultTheme='light' enableSystem>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
